# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

jobs:
  - job: dotnetjob
    displayName: 'Dotnet job'
    steps:
    - script: | 
        dotnet build --configuration $(buildConfiguration)
        dotnet test test/MbUtils.Extensions.Core.Tests --configuration $(buildConfiguration) --logger trx
      displayName: 'dotnet build&test $(buildConfiguration)'

    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'

    # Below are for tags branch only
    # conditioned with: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

  - script: |
      VERSION=$(echo $(Build.SourceBranch) | sed -e 's,.*/\(.*\),\1,')
      VERSION=$(echo $VERSION | sed -e 's/^v//')
      dotnet pack -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) -p:PackageVersion=$VERSION
      dotnet nuget push $(Build.ArtifactStagingDirectory)/**/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGETAPIKEY --no-symbols=true
    displayName: "dotnet pack & push"
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    env:
      NUGETAPIKEY: $(nugetApiKey)
