# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  major: '2'
  minor: '2'
  patch: '0'

steps:
- script: | 
    dotnet build --configuration $(buildConfiguration)
    dotnet test test/MbUtils.Extensions.Core.Tests --configuration $(buildConfiguration) --logger trx
  displayName: 'dotnet build&test $(buildConfiguration)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: NuGetCommand@2
  inputs:
    command: pack
    includeNuGetOrg: true
    majorVersion: '$(major)'
    minorVersion: '$(minor)'
    patchVersion: '$(patch)'